/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/sKbp6e8ZFHT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import Image from 'next/image';
import { MenuIcon } from '@heroicons/react/outline';
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { SpinningBorder } from "./ui/SpinningBorder";

import { projects } from "@/constants/Information";

export function Home() {
  const [theme, setTheme] = useState("light")
  const [dropdownOpen, setDropdownOpen] = useState(false)
  useEffect(() => {
    const systemTheme = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light"
    setTheme(systemTheme)
  }, [])
  return (
    <div className={`p-5 min-h-screen bg-background text-foreground transition-colors ${theme === "dark" ? "dark" : ""}`} onClick={() => {
      if(dropdownOpen) setDropdownOpen(false)
    }}>
      <header className="sticky top-0 z-50 bg-background/80 backdrop-blur-sm">
        <div className="container mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6 lg:px-8">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <Avatar className="h-8 w-8 border-golden-light">
              <AvatarFallback>BP</AvatarFallback>
            </Avatar>
            <span className="font-medium underline underline-offset-4">Basavaraj Patil</span>
          </Link>
          <div className="flex items-center gap-4">
            <div className="hidden sm:flex items-center gap-4">
              <Link href="#about" className="text-sm font-medium hover:underline" prefetch={false}>
                About
              </Link>
              <Link href="#education" className="text-sm font-medium hover:underline" prefetch={false}>
                Education
              </Link>
              <Link href="#skills" className="text-sm font-medium hover:underline" prefetch={false}>
                Skills
              </Link>
              <Link href="#experience" className="text-sm font-medium hover:underline" prefetch={false}>
                Experience
              </Link>
              <Link href="#projects" className="text-sm font-medium hover:underline" prefetch={false}>
                Projects
              </Link>
              <Link href="#contact" className="text-sm font-medium hover:underline" prefetch={false}>
                Contact
              </Link>
            </div>
            <Button className="rounded-full" variant="ghost" size="icon" onClick={() => setTheme(theme === "light" ? "dark" : "light")}>
              {theme === "light" ? <MoonIcon className="h-6 w-6" /> : <SunIcon className="h-6 w-6" />}
              <span className="sr-only">Toggle theme</span>
            </Button>
            <div className="relative">
              <Button variant="ghost" size="icon" className="sm:hidden rounded-full" onClick={() => setDropdownOpen(!dropdownOpen)}>
                <MenuIcon className="h-6 w-6" />
                <span className="sr-only">Open menu</span>
              </Button>
              {dropdownOpen && (
                <div className={`absolute right-0 mt-2 w-48 bg-background border ${theme === "dark" ? "border-gray-700" : "border-gray-200"} rounded shadow-lg sm:hidden transition-transform transform ${dropdownOpen ? 'scale-100' : 'scale-95'} ${dropdownOpen ? 'opacity-100' : 'opacity-0'} ${dropdownOpen ? 'translate-y-0' : '-translate-y-2'} transition duration-500`}>
                  <Link href="#about" className={`block px-4 py-2 text-sm cursor-pointer ${theme === "dark" ? "text-foreground hover:bg-gray-800" : "text-gray-700 hover:bg-gray-100"}`} prefetch={false} onClick={() => setDropdownOpen(false)}>
                    About
                  </Link>
                  <Link href="#education" className={`block px-4 py-2 text-sm cursor-pointer ${theme === "dark" ? "text-foreground hover:bg-gray-800" : "text-gray-700 hover:bg-gray-100"}`} prefetch={false} onClick={() => setDropdownOpen(false)}>
                    Education
                  </Link>
                  <Link href="#skills" className={`block px-4 py-2 text-sm cursor-pointer ${theme === "dark" ? "text-foreground hover:bg-gray-800" : "text-gray-700 hover:bg-gray-100"}`} prefetch={false} onClick={() => setDropdownOpen(false)}>
                    Skills
                  </Link>
                  <Link href="#experience" className={`block px-4 py-2 text-sm cursor-pointer ${theme === "dark" ? "text-foreground hover:bg-gray-800" : "text-gray-700 hover:bg-gray-100"}`} prefetch={false} onClick={() => setDropdownOpen(false)}>
                    Experience
                  </Link>
                  <Link href="#projects" className={`block px-4 py-2 text-sm cursor-pointer ${theme === "dark" ? "text-foreground hover:bg-gray-800" : "text-gray-700 hover:bg-gray-100"}`} prefetch={false} onClick={() => setDropdownOpen(false)}>
                    Projects
                  </Link>
                  <Link href="#contact" className={`block px-4 py-2 text-sm cursor-pointer ${theme === "dark" ? "text-foreground hover:bg-gray-800" : "text-gray-700 hover:bg-gray-100"}`} prefetch={false} onClick={() => setDropdownOpen(false)}>
                    Contact
                  </Link>
                </div>
              )}
            </div>
          </div>
        </div>
      </header>
      <main className="container mx-auto max-w-6xl px-4 py-12 sm:px-6 lg:px-8">
        <section id="about" className="mb-12">
          <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
            <div className="flex flex-col items-center justify-center">
              <SpinningBorder>
                <Avatar className="h-80 w-80">
                  <AvatarImage src="/profile.jpg" alt="Profile Image" />
                  <AvatarFallback>BP</AvatarFallback>
                </Avatar>
              </SpinningBorder>
              <div className="mt-6 flex space-x-8">
                <a href="https://linkedin.com/in/patilbasavaraj" target="_blank" rel="noopener noreferrer" className={`hover:text-blue-900 p-2 border-2 rounded-full ${theme === "dark" ? "text-blue-500 border-white" : "text-blue-700 border-black"}`}>
                  <LinkedInIcon className="h-10 w-10" />
                  <span className="sr-only">LinkedIn</span>
                </a>
                <a href="https://github.com/basupatil1213" target="_blank" rel="noopener noreferrer" className={`p-2 border-2 rounded-full ${theme === "dark" ? "text-gray-400 hover:text-white border-white" : "text-gray-800 hover:text-red-900 border-black"}`}>
                  <GitHubIcon className="h-10 w-10" />
                  <span className="sr-only">GitHub</span>
                </a>
                <a href="https://leetcode.com/u/basavaraj_patil/" target="_blank" rel="noopener noreferrer" className={`hover:text-orange-500 p-2 border-2 rounded-full ${theme === "dark" ? "text-orange-300 border-white" : "text-orange-500 border-black"}`}>
                  <LeetcodeIcon className="h-10 w-10" />
                  <span className="sr-only">Leetcode</span>
                </a>
              </div>
            </div>
            <div className="space-y-4">
              <h2 className="text-2xl font-bold">About Me</h2>
              <p className="text-muted-foreground">
                Hi, I&apos;m Basavaraj Patil, a passionate web developer with a keen eye for design. I specialize in creating
                modern, responsive, and user-friendly websites and applications.
              </p>
              <p className="text-muted-foreground">
                With several years of experience in the industry, I have developed a strong set of skills in Python, Java, JavaScript, and various front-end frameworks like React.js and Next.js. My technical expertise also extends to back-end development with Node.js and Express.js, as well as cloud platforms like Google Cloud Platform and Amazon Web Services. Additionally, I am proficient in using TypeScript, TailwindCSS, Terraform, and Packer. I am constantly learning and exploring new technologies to stay up-to-date with the latest trends and best practices.
              </p>
            </div>
          </div>
        </section>
        <section id="education" className="mb-12">
          <h2 className="mb-4 text-2xl font-bold">Education</h2>
          <div className="space-y-4">
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <div>
                <h3 className="text-lg font-semibold">Master of Science in Software Engineering</h3>
                <p className="text-muted-foreground">Northeastern University, Boston</p>
                <p className="text-muted-foreground">2023 - 2025</p>
              </div>
              <div>
                <h3 className="text-lg font-semibold">Bachelor of Engineering in Electronics & Communcation Engineering</h3>
                <p className="text-muted-foreground">Visvesvaraya Technological University, Bengaluru, India</p>
                <p className="text-muted-foreground">2017 - 2021</p>
              </div>
            </div>
          </div>
        </section>
        <section id="skills" className="mb-12">
          <h2 className="mb-4 text-2xl font-bold">Skills</h2>
          <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4">
            <div className="rounded bg-muted p-4 text-center">
              <JavaIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">Java</p>
            </div>
            <div className="rounded bg-muted p-4 text-center">
              <PythonIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">Python</p>
            </div>
            <div className="rounded bg-muted p-4 text-center">
              <HashIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">HTML</p>
            </div>
            <div className="rounded bg-muted p-4 text-center">
              <CodepenIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">CSS</p>
            </div>
            <div className="rounded bg-muted p-4 text-center">
              <CodepenIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">JavaScript</p>
            </div>
            <div className="rounded bg-muted p-4 text-center">
              <TypeScriptIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">TypeScript</p>
            </div>
            <div className="rounded bg-muted p-4 text-center">
              <CodepenIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">React</p>
            </div>
            <div className="rounded bg-muted p-4 text-center">
              <NextJSIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">Next.js</p>
            </div>
            <div className="rounded bg-muted p-4 text-center">
              <NetworkIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">Node.js</p>
            </div>
            <div className="rounded bg-muted p-4 text-center">
              <ExpressJSIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">Express.js</p>
            </div>
            <div className="rounded bg-muted p-4 text-center">
              <FigmaIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">Figma</p>
            </div>
            <div className="rounded bg-muted p-4 text-center">
              <GitGraphIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">Git</p>
            </div>
            <div className="rounded bg-muted p-4 text-center">
              <GithubIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">Github</p>
            </div>
            <div className="rounded bg-muted p-4 text-center">
              <AWSIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">AWS</p>
            </div>
            <div className="rounded bg-muted p-4 text-center">
              <GCPIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">GCP</p>
            </div>
            <div className="rounded bg-muted p-4 text-center">
              <TerraformIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">Terraform</p>
            </div>
            <div className="rounded bg-muted p-4 text-center">
              <PackerIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">Packer</p>
            </div>
          </div>
        </section>
        <section id="experience" className="mb-12">
          <h2 className="mb-4 text-2xl font-bold">Work Experience</h2>
          <div className="space-y-4">
            <div>
              <h3 className="text-lg font-semibold">Full Stack Developer</h3>
              <p className="text-muted-foreground">Koch Business Solutions India</p>
              <p className="text-muted-foreground">August 2021 - August 2023</p>
              <p className="text-muted-foreground">
              As a Software Full Stack Developer, I developed and optimized Salesforce applications using LWC, Apex, REST APIs, and RESTAPIS. I managed front-end development with HTML, CSS, JavaScript, and Salesforce Flows while handling back-end processes with Apex, Triggers, and pubsub. I implemented and maintained Sales Cloud, Service Cloud, and Experience Cloud solutions, enhancing user experience and operational efficiency.
              </p>
            </div>
            <div>
              <h3 className="text-lg font-semibold">Software Development Intern</h3>
              <p className="text-muted-foreground">Koch Business Solutions India</p>
              <p className="text-muted-foreground">March 2021 - June 2021</p>
              <p className="text-muted-foreground">
              During my tenure as a Software Developer Intern, I supported the development and optimization of Salesforce applications, working with LWC, Apex, REST APIs, and RESTAPIS. I engaged in front-end development using HTML, CSS, and JavaScript, and assisted with back-end tasks involving Apex, Salesforce Flows, and pubsub. My contributions included aiding in the implementation and maintenance of Sales Cloud, Service Cloud, and Experience Cloud solutions, with a focus on enhancing user experience and operational productivity.
              </p>
            </div>
          </div>
        </section>

        <section id="projects" className="mb-12">
          <h2 className="mb-4 text-2xl font-bold">Projects</h2>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3">
            {projects.map((project, idx) => {
              return (
                <Card className="h-[600px] flex flex-col justify-around gap-2 rounded" key={idx}>
              <div className="relative">
                <Image
                  src={project.display_img}//"/profile.jpg"
                  alt="Project 1"
                  width={600}
                  height={200}
                  className="rounded-t-lg object-cover"
                />
              </div>
              <CardHeader>
                <CardTitle>{project.title}</CardTitle>
                <CardDescription>{project.description}</CardDescription>
              </CardHeader>
              <CardContent className="h-1/4 flex-1 overflow-scroll">
                <p>{project.content}</p>
              </CardContent>
              <CardFooter className="flex items-center justify-center">
                <Link target="_blank" href={project.github_link} className="flex-1 inline-flex h-8 items-center justify-center rounded bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 rounded" prefetch={false}>
                  GitHub
                </Link>
                {project.demo_link && 
                <Link
                  href={project.demo_link}
                  className="inline-flex h-8 items-center justify-center rounded bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 rounded"
                  prefetch={false}
                >
                  Demo
                </Link>
                }
              </CardFooter>
            </Card>
              )
            })}
            {/* <Card className="h-full flex flex-col justify-around rounded">
              <div className="relative">
                <Image
                  src="/profile.jpg"
                  alt="Project 1"
                  width={600}
                  height={400}
                  className="rounded-t-lg object-cover"
                />
              </div>
              <CardHeader>
                <CardTitle>Project 1</CardTitle>
                <CardDescription>Lorem ipsum</CardDescription>
              </CardHeader>
              <CardContent className="flex-1 overflow-auto">
                <p>Lorem ipsum</p>
              </CardContent>
              <CardFooter className="flex items-center justify-between">
                <Link href="#" className="inline-flex h-8 items-center justify-center rounded bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 rounded" prefetch={false}>
                  GitHub
                </Link>
                <Link
                  href="#"
                  className="inline-flex h-8 items-center justify-center rounded bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 rounded"
                  prefetch={false}
                >
                  Demo
                </Link>
              </CardFooter>
            </Card>
            <Card className="h-full flex flex-col justify-around rounded">
              <div className="relative">
                <Image
                  src="/profile.jpg"
                  alt="Project 2"
                  width={600}
                  height={400}
                  className="rounded-t-lg object-cover"
                />
              </div>
              <CardHeader>
                <CardTitle>Project 2</CardTitle>
                <CardDescription>
                  A full-stack web application built with Node.js, Express, and MongoDB.
                </CardDescription>
              </CardHeader>
              <CardContent className="flex-1 overflow-scroll">
                <p>
                  This project demonstrates my expertise in building full-stack web applications using Node.js, Express,
                  and MongoDB. It features a robust backend API, secure authentication, and a responsive user interface.
                </p>
              </CardContent>
              <CardFooter className="flex items-center justify-between">
                <Link href="#" className="inline-flex h-8 items-center justify-center rounded bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 rounded" prefetch={false}>
                  GitHub
                </Link>
                <Link
                  href="#"
                  className="inline-flex h-8 items-center justify-center rounded bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 rounded"
                  prefetch={false}
                >
                  Demo
                </Link>
              </CardFooter>
            </Card>
            <Card className="h-full flex flex-col justify-around rounded">
              <div className="relative">
                <Image
                  src="/profile.jpg"
                  alt="Project 3"
                  width={600}
                  height={400}
                  className="rounded-t-lg object-cover"
                />
              </div>
              <CardHeader>
                <CardTitle>Project 3</CardTitle>
                <CardDescription>A mobile-first web application built with Vue.js and Ionic.</CardDescription>
              </CardHeader>
              <CardContent className="flex-1 overflow-auto">
                <p>
                  This project showcases my ability to create mobile-friendly web applications using Vue.js and Ionic.
                  It features a sleek and intuitive user interface, offline capabilities, and a range of native device
                  features.
                </p>
              </CardContent>
              <CardFooter className="flex items-center justify-between">
                <Link href="#" className="inline-flex h-8 items-center justify-center rounded bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 rounded" prefetch={false}>
                  GitHub
                </Link>
                <Link
                  href="#"
                  className="inline-flex h-8 items-center justify-center rounded bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 rounded"
                  prefetch={false}
                >
                  Demo
                </Link>
              </CardFooter>
            </Card>
            <Card className="h-full flex flex-col justify-around rounded">
              <div className="relative">
                <Image
                  src="/profile.jpg"
                  alt="Project 3"
                  width={600}
                  height={400}
                  className="rounded-t-lg object-cover"
                />
              </div>
              <CardHeader>
                <CardTitle>Project 3</CardTitle>
                <CardDescription>A mobile-first web application built with Vue.js and Ionic.</CardDescription>
              </CardHeader>
              <CardContent className="flex-1 overflow-auto">
                <p>
                  This project showcases my ability to create mobile-friendly web applications using Vue.js and Ionic.
                  It features a sleek and intuitive user interface, offline capabilities, and a range of native device
                  features.
                </p>
              </CardContent>
              <CardFooter className="flex items-center justify-between">
                <Link href="#" className="inline-flex h-8 items-center justify-center rounded bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 rounded" prefetch={false}>
                  GitHub
                </Link>
                <Link
                  href="#"
                  className="inline-flex h-8 items-center justify-center rounded bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 rounded"
                  prefetch={false}
                >
                  Demo
                </Link>
              </CardFooter>
            </Card> */}
          </div>
        </section>

        <section id="contact" className="mb-12">
          <h2 className="mb-4 text-2xl font-bold">Contact Me</h2>
          <form className={`space-y-4 border-2 p-8 ${theme == "dark" ? 'border-white' : 'border-black'} rounded`}>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <div>
                <Label htmlFor="name">Name</Label>
                <Input id="name" type="text" required />
              </div>
              <div>
                <Label htmlFor="email">Email</Label>
                <Input id="email" type="email" required />
              </div>
            </div>
            <div>
              <Label htmlFor="message">Message</Label>
              <Textarea id="message" rows={5} required />
            </div>
            <Button type="submit" className="w-full sm:w-auto rounded">
              Submit
            </Button>
          </form>
        </section>
      </main>
      <footer className="bg-muted py-4">
        <div className="container mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <p className="text-center text-sm text-muted-foreground">&copy; 2024 Basavaraj Patil. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}

function CodepenIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2" />
      <line x1="12" x2="12" y1="22" y2="15.5" />
      <polyline points="22 8.5 12 15.5 2 8.5" />
      <polyline points="2 15.5 12 8.5 22 15.5" />
      <line x1="12" x2="12" y1="2" y2="8.5" />
    </svg>
  )
}


function FigmaIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 5.5A3.5 3.5 0 0 1 8.5 2H12v7H8.5A3.5 3.5 0 0 1 5 5.5z" />
      <path d="M12 2h3.5a3.5 3.5 0 1 1 0 7H12V2z" />
      <path d="M12 12.5a3.5 3.5 0 1 1 7 0 3.5 3.5 0 1 1-7 0z" />
      <path d="M5 19.5A3.5 3.5 0 0 1 8.5 16H12v3.5a3.5 3.5 0 1 1-7 0z" />
      <path d="M5 12.5A3.5 3.5 0 0 1 8.5 9H12v7H8.5A3.5 3.5 0 0 1 5 12.5z" />
    </svg>
  )
}


function GitGraphIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="5" cy="6" r="3" />
      <path d="M5 9v6" />
      <circle cx="5" cy="18" r="3" />
      <path d="M12 3v18" />
      <circle cx="19" cy="6" r="3" />
      <path d="M16 15.7A9 9 0 0 0 19 9" />
    </svg>
  )
}

function GithubIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="currentColor"
      stroke="none"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2C6.48 2 2 6.48 2 12c0 4.418 2.867 8.164 6.839 9.486.5.092.68-.216.68-.48v-1.693c-2.782.605-3.369-1.342-3.369-1.342-.454-1.14-1.107-1.445-1.107-1.445-.906-.619.069-.607.069-.607 1.003.069 1.527 1.032 1.527 1.032.892 1.527 2.34 1.088 2.913.832.093-.647.348-1.088.635-1.339-2.22-.253-4.558-1.112-4.558-4.946 0-1.093.39-1.987 1.032-2.688-.103-.253-.448-1.268.095-2.641 0 0 .842-.271 2.758 1.034A9.572 9.572 0 0 1 12 7.78a9.572 9.572 0 0 1 2.759 1.034c1.916-1.305 2.758-1.034 2.758-1.034.543 1.373.198 2.388.095 2.641.642.701 1.032 1.595 1.032 2.688 0 3.844-2.343 4.688-4.573 4.938.357.308.676.91.676 1.832v2.71c0 .267.18.572.686.48A9.98 9.98 0 0 0 22 12c0-5.52-4.48-10-10-10z" />
    </svg>
  );
}



function HashIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="9" y2="9" />
      <line x1="4" x2="20" y1="15" y2="15" />
      <line x1="10" x2="8" y1="3" y2="21" />
      <line x1="16" x2="14" y1="3" y2="21" />
    </svg>
  )
}


function MoonIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />
    </svg>
  )
}


function NetworkIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="16" y="16" width="6" height="6" rx="1" />
      <rect x="2" y="16" width="6" height="6" rx="1" />
      <rect x="9" y="2" width="6" height="6" rx="1" />
      <path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3" />
      <path d="M12 12V8" />
    </svg>
  )
}

// Express Icon

function ExpressJSIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 12c0 5.5 8 10 8 10s8-4.5 8-10-8-10-8-10S2 6.5 2 12z" fill="currentColor" />
      <path d="M4 12l8-5.5L20 12l-8 5.5L4 12z" fill="none" stroke="currentColor" />
    </svg>
  );
}

//AWS Icon

function AWSIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 256 256"
      fill="currentColor"
      stroke="none"
    >
      <path d="M127.19 0C56.59 0 0 56.59 0 127.19s56.59 127.19 127.19 127.19c37.37 0 71.5-15.53 96.25-40.58l-14.87-18.7c-19.59 21.62-48.52 34.56-79.37 34.56-54.79 0-99.31-44.52-99.31-99.31s44.52-99.31 99.31-99.31c30.31 0 59.86 14.37 79.45 37.59l15.67-18.14C198.46 15.91 164.17 0 127.19 0zm-41.69 164.87v24.61c0 3.14 2.57 5.69 5.69 5.69s5.69-2.57 5.69-5.69v-24.61c0-3.14-2.57-5.69-5.69-5.69-3.12 0-5.69 2.55-5.69 5.69zm87.68-18.57c3.26 0 5.69-2.43 5.69-5.69v-24.61c0-3.14-2.43-5.69-5.69-5.69s-5.69 2.43-5.69 5.69v24.61c0 3.26 2.43 5.69 5.69 5.69zm6.73 2.42c-2.36 0-4.52-1.21-5.69-3.19-1.39-2.76-.34-6.07 2.42-7.36 2.76-1.39 6.07-.34 7.36 2.42 1.39 2.76.34 6.07-2.42 7.36-1.47.74-3.06 1.12-4.69 1.12zm53.67-33.22c-1.84 0-3.69-1.11-4.48-2.88-.55-1.24-.29-2.65.57-3.62.98-1.11 2.46-1.77 4.03-1.77 2.71 0 4.85 2.24 4.85 5.01 0 2.8-2.15 5.01-4.85 5.01-.51 0-1.01-.06-1.51-.17-1.67-.24-3.17-1.12-4.03-2.49-.54-1.21-.26-2.63.57-3.62.98-1.11 2.46-1.77 4.03-1.77 2.71 0 4.85 2.24 4.85 5.01 0 2.8-2.15 5.01-4.85 5.01-.51 0-1.01-.06-1.51-.17-1.67-.24-3.17-1.12-4.03-2.49-.54-1.21-.26-2.63.57-3.62.98-1.11 2.46-1.77 4.03-1.77 2.71 0 4.85 2.24 4.85 5.01 0 2.8-2.15 5.01-4.85 5.01-.51 0-1.01-.06-1.51-.17-1.67-.24-3.17-1.12-4.03-2.49-.54-1.21-.26-2.63.57-3.62.98-1.11 2.46-1.77 4.03-1.77 2.71 0 4.85 2.24 4.85 5.01 0 2.8-2.15 5.01-4.85 5.01zm2.95-39.86c-2.9 0-5.69 2.43-5.69 5.69v24.61c0 3.26 2.43 5.69 5.69 5.69 2.36 0 4.52-1.21 5.69-3.19 1.39-2.76.34-6.07-2.42-7.36-2.76-1.39-6.07-.34-7.36 2.42-1.39 2.76-.34 6.07 2.42 7.36 1.47.74 3.06 1.12 4.69 1.12 3.14 0 5.69-2.43 5.69-5.69v-24.61c0-3.14-2.55-5.69-5.69-5.69-2.36 0-4.52 1.21-5.69 3.19-1.39 2.76-.34 6.07 2.42 7.36 2.76 1.39 6.07.34 7.36-2.42 1.39-2.76.34-6.07-2.42-7.36-1.47-.74-3.06-1.12-4.69-1.12z" />
    </svg>
  );
}

//GCP Icon

function GCPIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="currentColor"
      stroke="none"
    >
      <path d="M12 2.5l-4.2 7.5 4.2 7.5 4.2-7.5L12 2.5zM12 4.35l2.2 3.8-2.2 4.1-2.2-4.1 2.2-3.8zM3.5 12c0 2.2 1.8 4 4 4 1.5 0 2.8-.8 3.5-2 1.5.7 3.3 1.2 5.2 1.2 2.2 0 4-1.8 4-4s-1.8-4-4-4c-1.9 0-3.6.6-5.2 1.7-1.2-1.2-2.8-2-4.5-2-2.2 0-4 1.8-4 4z" />
    </svg>
  );
}

// Terraform ICon

function TerraformIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="currentColor"
      stroke="none"
    >
      <path d="M12 2L3 8l9 6 9-6-9-6zm0 20l9-6-9-6-9 6 9 6zm0-8.5L3 8l9-6 9 6-9 6z" />
    </svg>
  );
}

// Packer Icon

function PackerIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="currentColor"
      stroke="none"
    >
      <path d="M2 12L12 2l10 10-10 10L2 12zm10-7.07L3.93 12 12 20.07 20.07 12 12 4.93z" />
    </svg>
  );
}

// TypeScipt Icon

function TypeScriptIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 128 128"
      fill="currentColor"
      stroke="none"
    >
      <path d="M44.1 49.5l-7.7 17.5h-5l7.7-17.5h5zm-6.2 26.7h5.3l-7.7-17.6-7.7 17.6h5.3zm27.7-8.2v-4.7h-6.7v4.7h-5.1v-14h11.8v4.7h-6.7v4.9h5.1v4.7h5.1zm30.3-4.4c-.3-.4-.7-.7-1.2-.9-.6-.3-1.3-.5-2.1-.5-1.4 0-2.6.5-3.5 1.3-1 .9-1.5 2.1-1.5 3.5v.2c0 1.4.5 2.6 1.5 3.5 1 .9 2.2 1.4 3.5 1.4 1.4 0 2.6-.5 3.5-1.4.9-.9 1.4-2.1 1.4-3.5 0-1.4-.5-2.6-1.4-3.5zm-2.3 5.2c-.8.8-1.8 1.2-2.8 1.2-1.1 0-2.1-.4-2.8-1.2-.8-.8-1.2-1.8-1.2-2.9v-.2c0-1.1.4-2.1 1.2-2.9.7-.8 1.7-1.2 2.8-1.2 1.1 0 2.1.4 2.8 1.2.8.8 1.2 1.8 1.2 2.9 0 1.1-.4 2.1-1.2 2.9zM63.1 2H11.3C5.5 2 1 6.5 1 12.3v103.5c0 5.8 4.5 10.3 10.3 10.3h51.8c5.8 0 10.3-4.5 10.3-10.3V12.3C73.4 6.5 68.9 2 63.1 2zm0 15.7h-4.2c-2.5 0-4.7 1-6.4 2.8l-7.1 6.8-7.1-6.8c-1.7-1.8-4-2.8-6.4-2.8h-4.2c-3.5 0-6.4 2.8-6.4 6.4v78.8c0 3.5 2.8 6.4 6.4 6.4h4.2c2.5 0 4.7-1 6.4-2.8l7.1-6.8 7.1 6.8c1.7 1.8 4 2.8 6.4 2.8h4.2c3.5 0 6.4-2.8 6.4-6.4v-78.8c0-3.5-2.8-6.4-6.4-6.4z" />
    </svg>
  );
}

//TailwindCSS Icon

function TailwindIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 256 256"
      fill="currentColor"
    >
      <path d="M204.8 51.2C169.8 16.2 120.2 0 72 0 32.2 0 0 32.2 0 72c0 9.9 2.2 19.6 5.8 28.4-4.5 8.1-7.8 17.5-7.8 27.6 0 39.8 32.2 72 72 72 6.2 0 12.3-.8 18.2-2.3 4.5 10.4 10.5 19.9 18.1 27.5 8.1 8.1 17.7 14.8 28.1 19.4 7.3 3.2 15.3 4.9 23.4 4.9 39.8 0 72-32.2 72-72 0-15.8-4.8-30.6-12.9-43.2 5.2-10.2 8.7-21.9 8.7-34.5 0-39.8-32.2-72-72-72-8.8 0-17.4 1.7-25.4 4.7-7.7-11.3-18.2-21-30.7-27.7zM72 16c27.7 0 52.3 13.6 67.1 33.5-22.5 17.3-39.8 42.4-51.3 69.5-7.2 18.1-11.2 38.3-11.2 58.6 0 5.7.4 11.3 1.1 16.8-7.5-6.8-13.7-14.6-18.7-23.3-8.8-15.2-14.4-32.3-17.8-50.5C17.6 72.7 16 64.3 16 56c0-27.7 22.5-50.2 50.2-50.2zm96.1 22.6c9.2-7.6 21.1-12.2 33.4-12.2 27.7 0 50.2 22.5 50.2 50.2 0 9.6-2.7 18.9-7.6 27.2-14.1-6.2-29.7-10.1-46.5-10.1-8.4 0-16.5.9-24.4 2.5-1.2-8.8-3.4-17.2-6.8-25.1-4.3-9.7-10-19.1-16.9-27.1 11.4-4.4 23.7-6.9 36.7-6.9 13.6 0 26.6 2.7 38.5 7.8 7.1 2.9 13.4 7.2 18.8 12.7 6.6 6.6 11.8 14.3 15.4 22.9-13.1 4.1-25.9 9.8-37.9 16.9-2.2 1.5-4.2 3.1-6.2 4.7-8.3 6.2-15.7 13.5-22.2 21.7-8.5 11.3-15.3 23.7-20.1 36.8-6.1-11.3-13.2-21.6-21.7-31.4-8.2-8.5-17.4-16.2-27.5-22.6 7.7-12.3 17.4-23.5 28.8-33.2 8.7-7.5 18.5-14.2 28.9-19.8zm-46.8 34.7c5.6 13.4 10.9 26.9 16.1 40.5 4.8 11.6 9.4 23.3 14 35.1 3.9 9.2 7.5 18.4 11.2 27.6-6.3 5.8-12.5 11.2-19.5 16.1-8.6 6.4-18.3 11.9-28.2 16.3-2.5-9.8-6.5-19.1-11.4-27.9-4.5-7.4-9.3-14.5-14.7-21.6-3.7-5.4-7.3-10.9-11.2-16.1-6.4-8.6-13.5-16.4-21.8-23.3-7.6-6.4-15.9-12.2-24.8-17.2 8.8-14.6 20.1-27.8 32.3-39.4 7.9-7.7 16.4-14.9 25.7-21.2 11.7-8.2 24.3-15.1 37.8-21.1-3.2 7.7-6.5 15.4-9.5 23.3-5.4 15.6-11.3 31-17.9 46.2z" />
    </svg>
  );
}


// Java Icon

function JavaIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 256 256"
      fill="currentColor"
    >
      <path d="M128 32c-52.93 0-96 43.07-96 96s43.07 96 96 96 96-43.07 96-96-43.07-96-96-96zm0 160c-10.97 0-20-9.03-20-20s9.03-20 20-20 20 9.03 20 20-9.03 20-20 20zm16.56-20.62c0 16.92-13.73 30.56-30.56 30.56s-30.56-13.64-30.56-30.56c0-14.18 9.6-26.41 22.34-30.41v-15.92c-12.75-4.06-22.32-16.15-22.32-30.65 0-17.72 14.37-32 32-32 10.84 0 20.66 5.49 27.18 13.59 3.28 4.03 5.34 9.09 5.34 14.63 0 12.77-10.49 23.09-23.29 23.09-8.48 0-15.36-5.45-18.4-13.14 2.58 2.04 5.46 3.15 8.38 3.15 6.85 0 12.42-5.58 12.42-12.42 0-2.79-1.06-5.35-2.74-7.27 3.16 1.46 6.85 2.32 10.48 2.32 6.57 0 11.88-5.31 11.88-11.88 0-4.28-2.08-8.21-5.34-10.56-4.99-2.98-10.66-4.71-16.56-4.71-13.18 0-23.79 10.37-23.79 23.79 0 11.51 8.87 20.97 20.03 22.78 2.43.38 4.79 1.12 6.85 2.26 3.27 2.25 5.47 5.68 5.47 9.74zM112 104c-8.84 0-16-7.16-16-16s7.16-16 16-16 16 7.16 16 16-7.16 16-16 16z" />
    </svg>
  );
}

//Python Icon

function PythonIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
      fill="currentColor"
    >
      <path d="M45.6 10.4c-4.8-4.8-11.2-7.5-18.4-7.5-9.3 0-17 4.5-22 11.5-2.7 3.2-4.6 7-5.6 11.2-.4 1.7-.6 3.5-.6 5.3v5.4c0 1.8.2 3.6.6 5.3 1 4.2 2.9 8 5.6 11.2 5 7 12.7 11.5 22 11.5 7.2 0 13.6-2.7 18.4-7.5 4.8-4.8 7.5-11.2 7.5-18.4 0-7.2-2.7-13.6-7.5-18.4zM40 28H24v8h10.5c-1.5 2.7-4.2 4.5-7.3 4.5-4.8 0-8.8-3.9-8.8-8.8s3.9-8.8 8.8-8.8c3.1 0 5.8 1.8 7.3 4.5H24v-8h16v8zM32 36c0-2.7 2.2-4.8 4.8-4.8 2.7 0 4.8 2.2 4.8 4.8s-2.2 4.8-4.8 4.8c-2.7 0-4.8-2.2-4.8-4.8zM32 8c-2.7 0-4.8 2.2-4.8 4.8s2.2 4.8 4.8 4.8c2.7 0 4.8-2.2 4.8-4.8s-2.2-4.8-4.8-4.8zM16 16H8c0-6.4 5.2-11.5 11.5-11.5 4.1 0 7.7 1.7 10.3 4.5h-9c-4.8 0-8.8 3.9-8.8 8.8s3.9 8.8 8.8 8.8h10v-8h-6.2c-1.6-2.7-4.2-4.5-7.3-4.5-2.7 0-4.8-2.2-4.8-4.8zM48 48c-2.7 0-4.8-2.2-4.8-4.8s2.2-4.8 4.8-4.8c2.7 0 4.8 2.2 4.8 4.8s-2.2 4.8-4.8 4.8z" />
    </svg>
  );
}



function SunIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}


function ViewIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12s2.545-5 7-5c4.454 0 7 5 7 5s-2.546 5-7 5c-4.455 0-7-5-7-5z" />
      <path d="M12 13a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
      <path d="M21 17v2a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-2" />
      <path d="M21 7V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v2" />
    </svg>
  )
}

function NextJSIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 256 256"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M128 40L40 128l88 88 88-88L128 40z" fill="currentColor" />
      <path d="M128 216V40l88 88-88 88-88-88 88-88v176z" fill="none" stroke="currentColor" strokeWidth="2" />
    </svg>
  );
}


function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}


// TwitterIcon
function TwitterIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="currentColor"
    >
      <path d="M23.954 4.569c-.885.392-1.83.656-2.825.775 1.014-.611 1.794-1.574 2.163-2.723-.949.555-2.005.959-3.127 1.184-.897-.959-2.178-1.559-3.594-1.559-2.717 0-4.92 2.203-4.92 4.917 0 .39.045.765.127 1.124-4.087-.205-7.713-2.165-10.141-5.144-.422.722-.666 1.561-.666 2.475 0 1.71.87 3.213 2.188 4.096-.807-.026-1.566-.248-2.228-.616v.061c0 2.385 1.693 4.374 3.946 4.827-.413.111-.849.171-1.296.171-.314 0-.615-.03-.916-.086.631 1.953 2.445 3.377 4.604 3.417-1.68 1.319-3.809 2.105-6.102 2.105-.39 0-.779-.023-1.17-.067 2.189 1.394 4.768 2.209 7.557 2.209 9.054 0 14-7.496 14-13.986 0-.21 0-.423-.015-.634.961-.695 1.8-1.562 2.46-2.549z" />
    </svg>
  );
}

// linkedIn Icon

function LinkedInIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="currentColor"
    >
      <path d="M19 0h-14c-2.76 0-5 2.24-5 5v14c0 2.76 2.24 5 5 5h14c2.76 0 5-2.24 5-5v-14c0-2.76-2.24-5-5-5zm-11 19h-3v-10h3v10zm-1.5-11.28c-.97 0-1.75-.79-1.75-1.75s.78-1.75 1.75-1.75 1.75.79 1.75 1.75-.78 1.75-1.75 1.75zm13.5 11.28h-3v-5.6c0-1.34-.03-3.07-1.87-3.07-1.87 0-2.16 1.46-2.16 2.97v5.7h-3v-10h2.88v1.36h.04c.4-.75 1.38-1.54 2.84-1.54 3.04 0 3.6 2 3.6 4.59v5.59z" />
    </svg>
  );
}



// GitHubIcon 

function GitHubIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="currentColor"
    >
      <path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.387.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61-.546-1.387-1.333-1.757-1.333-1.757-1.09-.744.083-.729.083-.729 1.205.084 1.84 1.236 1.84 1.236 1.07 1.835 2.807 1.305 3.492.998.108-.775.418-1.305.76-1.605-2.665-.305-5.466-1.332-5.466-5.93 0-1.31.467-2.38 1.235-3.22-.123-.303-.535-1.523.117-3.176 0 0 1.008-.322 3.3 1.23.957-.266 1.983-.399 3.005-.404 1.02.005 2.048.138 3.006.404 2.29-1.552 3.297-1.23 3.297-1.23.653 1.653.241 2.873.118 3.176.77.84 1.233 1.91 1.233 3.22 0 4.61-2.803 5.62-5.475 5.92.43.37.823 1.102.823 2.222 0 1.606-.014 2.896-.014 3.286 0 .322.218.694.825.576C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12" />
    </svg>
  );
}

//LeetcodeIcon

function LeetcodeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="currentColor"
    >
      <path fill="#B3B1B0" d="M22 14.355c0-.742-.564-1.346-1.26-1.346H10.676c-.696 0-1.26.604-1.26 1.346s.563 1.346 1.26 1.346H20.74c.696.001 1.26-.603 1.26-1.346z"></path><path fill="#E7A41F" d="m3.482 18.187 4.313 4.361c.973.979 2.318 1.452 3.803 1.452 1.485 0 2.83-.512 3.805-1.494l2.588-2.637c.51-.514.492-1.365-.039-1.9-.531-.535-1.375-.553-1.884-.039l-2.676 2.607c-.462.467-1.102.662-1.809.662s-1.346-.195-1.81-.662l-4.298-4.363c-.463-.467-.696-1.15-.696-1.863 0-.713.233-1.357.696-1.824l4.285-4.38c.463-.467 1.116-.645 1.822-.645s1.346.195 1.809.662l2.676 2.606c.51.515 1.354.497 1.885-.038.531-.536.549-1.387.039-1.901l-2.588-2.636a4.994 4.994 0 0 0-2.392-1.33l-.034-.007 2.447-2.503c.512-.514.494-1.366-.037-1.901-.531-.535-1.376-.552-1.887-.038l-10.018 10.1C2.509 11.458 2 12.813 2 14.311c0 1.498.509 2.896 1.482 3.876z"></path><path fill="#070706" d="M8.115 22.814a2.109 2.109 0 0 1-.474-.361c-1.327-1.333-2.66-2.66-3.984-3.997-1.989-2.008-2.302-4.937-.786-7.32a6 6 0 0 1 .839-1.004L13.333.489c.625-.626 1.498-.652 2.079-.067.56.563.527 1.455-.078 2.066-.769.776-1.539 1.55-2.309 2.325-.041.122-.14.2-.225.287-.863.876-1.75 1.729-2.601 2.618-.111.116-.262.186-.372.305-1.423 1.423-2.863 2.83-4.266 4.272-1.135 1.167-1.097 2.938.068 4.127 1.308 1.336 2.639 2.65 3.961 3.974.067.067.136.132.204.198.468.303.474 1.25.183 1.671-.321.465-.74.75-1.333.728-.199-.006-.363-.086-.529-.179z"></path>
    </svg>
  );
}